total_semantic_labels: 41  # Total labels in NYUD40 (index 0 to 40)
dynamic_labels: [31]  # Add dynamic labels if any
invalid_labels: []  # Add invalid labels if any
object_labels:  # Add labels corresponding to objects
  - 3  # cabinet
  - 4  # bed
  - 5  # chair
  - 6  # sofa
  - 7  # table
  - 8  # door
  - 9  # window
  - 10  # bookshelf
  - 11  # picture
  - 12  # counter
  - 13  # blinds
  - 14  # desk
  - 15  # shelves
  - 16  # curtain
  - 17  # dresser
  - 18  # pillow
  - 19  # mirror
  - 20  # floor mat
  - 21  # clothes
  - 23  # fridge
  - 24  # tv
  - 27  # shower curtain
  - 30  # whiteboard
  - 32  # nightstand
  - 33  # toilet
  - 34  # sink
  - 36  # bathtub
  - 37  # bag
  - 38  # otherstructure
  - 39  # otherfurniture
  - 40  # otherprop
surface_places_labels:  # Add labels corresponding to surfaces
  - 1  # wall
  - 2  # floor
  - 17  # ceiling
label_names:
  - {label: 0, name: Unknown}
  - {label: 1, name: wall}
  - {label: 2, name: floor}
  - {label: 3, name: cabinet}
  - {label: 4, name: bed}
  - {label: 5, name: chair}
  - {label: 6, name: sofa}
  - {label: 7, name: table}
  - {label: 8, name: door}
  - {label: 9, name: window}
  - {label: 10, name: bookshelf}
  - {label: 11, name: picture}
  - {label: 12, name: counter}
  - {label: 13, name: blinds}
  - {label: 14, name: desk}
  - {label: 15, name: shelves}
  - {label: 16, name: curtain}
  - {label: 17, name: dresser}
  - {label: 18, name: pillow}
  - {label: 19, name: mirror}
  - {label: 20, name: floor mat}
  - {label: 21, name: clothes}
  - {label: 22, name: ceiling}
  - {label: 23, name: books}
  - {label: 24, name: fridge}
  - {label: 25, name: tv}
  - {label: 26, name: paper}
  - {label: 27, name: towel}
  - {label: 28, name: shower curtain}
  - {label: 29, name: box}
  - {label: 30, name: whiteboard}
  - {label: 31, name: person}
  - {label: 32, name: nightstand}
  - {label: 33, name: toilet}
  - {label: 34, name: sink}
  - {label: 35, name: lamp}
  - {label: 36, name: bathtub}
  - {label: 37, name: bag}
  - {label: 38, name: otherstructure}
  - {label: 39, name: otherfurniture}
  - {label: 40, name: otherprop}
